# Configuration file for LE-VINS

# 结果输出路径
outputpath: ""
is_make_outputdir: true

# 是否开启可视化
is_use_visualization: true

# ROS接口配置
ros:
    imu_topic: "/livox/imu"
    image_topic: "/cam0"
    lidar_topic: "/livox/lidar"
    use_compressed_image: true # 使用压缩图像

    # 读取ROS包
    is_read_bag: true
    bag_file: ""

# IMU噪声建模参数
imu:
    imudatarate: 200 # IMU原始数据频率, Hz
    is_use_zupt: true # 使用零速检测和零速约束

    arw: 0.5 # deg/sqrt(hr)
    vrw: 1.0 # m/s/sqrt(hr)
    gbstd: 50 # deg/hr
    abstd: 100 # mGal
    corrtime: 1.0 # hr

    gb_prior_std: 1500 # deg/hr
    ab_prior_std: 15000 # mGal

# 优化器
optimizer:
    optimize_reprojection_std: 1.5 # 像素重投影误差
    optimize_point_to_plane_std: 0.1 # 点到面观测协方差, m
    optimize_window_size: 10 # 滑动窗口大小

    optimize_estimate_cam_extrinsic: true # 是否估计相机和IMU的外参
    optimize_estimate_cam_td: true # 是否估计相机和IMU之间的时间间隔
    optimize_cam_extrinsic_accurate: true # 相机和IMU的外参初值准确

visual:
    is_use_lidar_depth: true # 使用激光深度增强
    track_max_features: 200 # 最大提取特征数量

     # 内参 [fx, fy, cx, cy(, skew)]
    intrinsic: [863.4241, 863.4171, 640.6808, 518.3392]

    # 畸变参数 [k1, k2, p1, p2(, k3)]
    distortion: [-0.1080, 0.1050, -1.2872e-04, 5.7923e-05, -0.0222]

    # 图像分辨率
    resolution: [1280, 1024]

    # 相机IMU外参 Pb = q_b_c * Pc + t_b_c
    # q (x, y, z, w)
    q_b_c: [0.499629, 0.504424, 0.495035, 0.500867]
    t_b_c: [0.058, -0.069, 0.013]

    # IMU和相机时间延时
    # t_b = t_c + td
    # TODO: hkust-campus0: 0.01 hkust-campus1: 0.06 hkust-campus2: 0.015
    #       hku-main-building: 0.0 hku-park0: 0.06 hku-park1: 0.02
    td_b_c: 0.0

    # 激光相机外参 Pc = q_c_l * Pl + t_c_l
    # q (x, y, z, w)
    q_c_l: [-0.4991117338677414, 0.5062278362608855, -0.49440996678462257, -0.5001796073953708]
    t_c_l: [0.04183047861925253, 0.005597350405590019, -0.10409073314623786]

    # t_b = t_l + td
    td_b_l: 0.0

lidar:
    # 激光参数
    lidar_type: 1 # Livox: 1; Velodyne: 2; Ouster: 3
    scan_line: 6 # 扫描线数
    nearest_distance: 1 # 扫描盲区, m
    farthest_distance: 250.0 # 最远距离, m
    frame_rate: 10 # 帧率, Hz